name: CI

env:
  go-version: "1.19"
  node-version: "16"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: make install

      - name: Setup PATH for wasm
        run: echo "${{env.GOROOT}}/misc/wasm" >> $GITHUB_PATH

      - name: build wasm
        run: make build-wasm
      - name: test go
        run: make test-go

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "yarn"

      - name: build js
        run: make build-js

      - name: test js
        run: make test-js
